//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Input/DoomControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DoomControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DoomControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DoomControls"",
    ""maps"": [
        {
            ""name"": ""Doom_Default"",
            ""id"": ""451759d0-7af3-4f52-9f72-f166cafe9f58"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""613a5ac5-2cc7-44eb-8ea7-d90825404ff2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Aiming"",
                    ""type"": ""Value"",
                    ""id"": ""5844cf3c-4115-4d94-a783-4cb573e00b2a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""e08c9044-6195-4655-b16b-532eaf8146a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""46e556af-5753-4f7d-ad4c-92cd832b3ccd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CycleWeaponDown"",
                    ""type"": ""Button"",
                    ""id"": ""b1b0b484-083f-4f2a-8161-0b2104d6f6c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CycleWeaponUp"",
                    ""type"": ""Button"",
                    ""id"": ""780532d2-a216-46c2-9653-34396b6ea179"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AimingController"",
                    ""type"": ""Button"",
                    ""id"": ""04ed3359-4c0e-42d6-967e-389b99724703"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MeleeEquip"",
                    ""type"": ""Button"",
                    ""id"": ""b2421c60-7d46-42df-8e8e-0a56228f9f11"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpeedBoost"",
                    ""type"": ""Button"",
                    ""id"": ""9fc64928-cbbb-4adf-8d6f-ed23a07b7154"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1a35da32-6187-4232-bc1b-06b21675188d"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""92f8a96e-4e5c-4f75-9227-2c285051e0c5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""922a1270-338c-49c3-a50f-6e3608b3504c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a54338eb-1872-44ed-acc4-76295dcd8772"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""de68e4ad-4ac8-45ec-921e-19ad942e3d3f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4c1da9c9-659a-49a5-a3ec-b2f2f43eb518"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1eee514c-5060-4098-9c4d-1e86958bd75c"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse"",
                    ""action"": ""Aiming"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3806f674-c11f-4122-b822-a47673b36313"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc3cfff8-a84a-41aa-ad95-a4d060a4c5af"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0a69bf5-2f7c-413d-9de7-343fccfc4f69"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d2e5bcb2-a80e-4b47-92c4-ec164f141b06"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1cad4a6b-c495-4784-bfe9-e6d26760feeb"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse"",
                    ""action"": ""CycleWeaponDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3e69cf75-0aeb-48f1-80f4-e42645a75f48"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""CycleWeaponDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d032e60-10f3-42f7-8f72-0a024028b49e"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse"",
                    ""action"": ""CycleWeaponUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef06891e-f3d3-4eb3-b096-6bba2ef6acc5"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""CycleWeaponUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85c5e903-2dfa-474c-8ded-7c9c0a0dce99"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""AimingController"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c0bce2a-3da0-4d6c-a3e7-900f3d30177b"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse"",
                    ""action"": ""MeleeEquip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15eb93eb-b9f1-44ff-a5a1-abbf59bcd467"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""MeleeEquip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba228854-2a3f-4a06-bd34-747351ada342"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Hold(duration=4)"",
                    ""processors"": """",
                    ""groups"": ""Mouse"",
                    ""action"": ""SpeedBoost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f77e289b-c55b-4590-8fd9-0691352faa7d"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": ""Hold(duration=4)"",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""SpeedBoost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Mouse"",
            ""bindingGroup"": ""Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Controller"",
            ""bindingGroup"": ""Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Doom_Default
        m_Doom_Default = asset.FindActionMap("Doom_Default", throwIfNotFound: true);
        m_Doom_Default_Movement = m_Doom_Default.FindAction("Movement", throwIfNotFound: true);
        m_Doom_Default_Aiming = m_Doom_Default.FindAction("Aiming", throwIfNotFound: true);
        m_Doom_Default_Attack = m_Doom_Default.FindAction("Attack", throwIfNotFound: true);
        m_Doom_Default_Interact = m_Doom_Default.FindAction("Interact", throwIfNotFound: true);
        m_Doom_Default_CycleWeaponDown = m_Doom_Default.FindAction("CycleWeaponDown", throwIfNotFound: true);
        m_Doom_Default_CycleWeaponUp = m_Doom_Default.FindAction("CycleWeaponUp", throwIfNotFound: true);
        m_Doom_Default_AimingController = m_Doom_Default.FindAction("AimingController", throwIfNotFound: true);
        m_Doom_Default_MeleeEquip = m_Doom_Default.FindAction("MeleeEquip", throwIfNotFound: true);
        m_Doom_Default_SpeedBoost = m_Doom_Default.FindAction("SpeedBoost", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Doom_Default
    private readonly InputActionMap m_Doom_Default;
    private IDoom_DefaultActions m_Doom_DefaultActionsCallbackInterface;
    private readonly InputAction m_Doom_Default_Movement;
    private readonly InputAction m_Doom_Default_Aiming;
    private readonly InputAction m_Doom_Default_Attack;
    private readonly InputAction m_Doom_Default_Interact;
    private readonly InputAction m_Doom_Default_CycleWeaponDown;
    private readonly InputAction m_Doom_Default_CycleWeaponUp;
    private readonly InputAction m_Doom_Default_AimingController;
    private readonly InputAction m_Doom_Default_MeleeEquip;
    private readonly InputAction m_Doom_Default_SpeedBoost;
    public struct Doom_DefaultActions
    {
        private @DoomControls m_Wrapper;
        public Doom_DefaultActions(@DoomControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Doom_Default_Movement;
        public InputAction @Aiming => m_Wrapper.m_Doom_Default_Aiming;
        public InputAction @Attack => m_Wrapper.m_Doom_Default_Attack;
        public InputAction @Interact => m_Wrapper.m_Doom_Default_Interact;
        public InputAction @CycleWeaponDown => m_Wrapper.m_Doom_Default_CycleWeaponDown;
        public InputAction @CycleWeaponUp => m_Wrapper.m_Doom_Default_CycleWeaponUp;
        public InputAction @AimingController => m_Wrapper.m_Doom_Default_AimingController;
        public InputAction @MeleeEquip => m_Wrapper.m_Doom_Default_MeleeEquip;
        public InputAction @SpeedBoost => m_Wrapper.m_Doom_Default_SpeedBoost;
        public InputActionMap Get() { return m_Wrapper.m_Doom_Default; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Doom_DefaultActions set) { return set.Get(); }
        public void SetCallbacks(IDoom_DefaultActions instance)
        {
            if (m_Wrapper.m_Doom_DefaultActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnMovement;
                @Aiming.started -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnAiming;
                @Aiming.performed -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnAiming;
                @Aiming.canceled -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnAiming;
                @Attack.started -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnAttack;
                @Interact.started -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnInteract;
                @CycleWeaponDown.started -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnCycleWeaponDown;
                @CycleWeaponDown.performed -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnCycleWeaponDown;
                @CycleWeaponDown.canceled -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnCycleWeaponDown;
                @CycleWeaponUp.started -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnCycleWeaponUp;
                @CycleWeaponUp.performed -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnCycleWeaponUp;
                @CycleWeaponUp.canceled -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnCycleWeaponUp;
                @AimingController.started -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnAimingController;
                @AimingController.performed -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnAimingController;
                @AimingController.canceled -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnAimingController;
                @MeleeEquip.started -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnMeleeEquip;
                @MeleeEquip.performed -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnMeleeEquip;
                @MeleeEquip.canceled -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnMeleeEquip;
                @SpeedBoost.started -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnSpeedBoost;
                @SpeedBoost.performed -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnSpeedBoost;
                @SpeedBoost.canceled -= m_Wrapper.m_Doom_DefaultActionsCallbackInterface.OnSpeedBoost;
            }
            m_Wrapper.m_Doom_DefaultActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Aiming.started += instance.OnAiming;
                @Aiming.performed += instance.OnAiming;
                @Aiming.canceled += instance.OnAiming;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @CycleWeaponDown.started += instance.OnCycleWeaponDown;
                @CycleWeaponDown.performed += instance.OnCycleWeaponDown;
                @CycleWeaponDown.canceled += instance.OnCycleWeaponDown;
                @CycleWeaponUp.started += instance.OnCycleWeaponUp;
                @CycleWeaponUp.performed += instance.OnCycleWeaponUp;
                @CycleWeaponUp.canceled += instance.OnCycleWeaponUp;
                @AimingController.started += instance.OnAimingController;
                @AimingController.performed += instance.OnAimingController;
                @AimingController.canceled += instance.OnAimingController;
                @MeleeEquip.started += instance.OnMeleeEquip;
                @MeleeEquip.performed += instance.OnMeleeEquip;
                @MeleeEquip.canceled += instance.OnMeleeEquip;
                @SpeedBoost.started += instance.OnSpeedBoost;
                @SpeedBoost.performed += instance.OnSpeedBoost;
                @SpeedBoost.canceled += instance.OnSpeedBoost;
            }
        }
    }
    public Doom_DefaultActions @Doom_Default => new Doom_DefaultActions(this);
    private int m_MouseSchemeIndex = -1;
    public InputControlScheme MouseScheme
    {
        get
        {
            if (m_MouseSchemeIndex == -1) m_MouseSchemeIndex = asset.FindControlSchemeIndex("Mouse");
            return asset.controlSchemes[m_MouseSchemeIndex];
        }
    }
    private int m_ControllerSchemeIndex = -1;
    public InputControlScheme ControllerScheme
    {
        get
        {
            if (m_ControllerSchemeIndex == -1) m_ControllerSchemeIndex = asset.FindControlSchemeIndex("Controller");
            return asset.controlSchemes[m_ControllerSchemeIndex];
        }
    }
    public interface IDoom_DefaultActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnAiming(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnCycleWeaponDown(InputAction.CallbackContext context);
        void OnCycleWeaponUp(InputAction.CallbackContext context);
        void OnAimingController(InputAction.CallbackContext context);
        void OnMeleeEquip(InputAction.CallbackContext context);
        void OnSpeedBoost(InputAction.CallbackContext context);
    }
}
